Repository hazelcast/hazelcast-client-protocol, pull requests merged in 2020-01, with the labels that each got.

#288 Remove redundant isFailoverSupportedMessage
  protocol-definitions/Client.yaml
Labels: 2.x

#283 Add missing docs
  java/codec-template.java.j2
  protocol-definitions/AtomicLong.yaml
  protocol-definitions/CPSession.yaml
  protocol-definitions/Cache.yaml
  protocol-definitions/Client.yaml
  protocol-definitions/ContinuousQuery.yaml
  protocol-definitions/DynamicConfig.yaml
  protocol-definitions/ExecutorService.yaml
  protocol-definitions/FencedLock.yaml
  protocol-definitions/FlakeIdGenerator.yaml
  protocol-definitions/List.yaml
  protocol-definitions/Map.yaml
  protocol-definitions/MultiMap.yaml
  protocol-definitions/PNCounter.yaml
  protocol-definitions/Queue.yaml
  protocol-definitions/ReplicatedMap.yaml
  protocol-definitions/Ringbuffer.yaml
  protocol-definitions/ScheduledExecutor.yaml
  protocol-definitions/Set.yaml
  protocol-definitions/Topic.yaml
  protocol-definitions/Transaction.yaml
  protocol-definitions/XATransaction.yaml
Labels: 2.x, Documentation

#293 reduce backup acks field size
  binary/constants.py
  java/codec-template.java.j2
Labels: 2.x

#294 simplify binary generator and remove enum types
  README.md
  binary/__init__.py
  binary/reference_objects.py
  binary/util.py
  binary_generator.py
  cs/__init__.py
  java/__init__.py
  protocol-definitions/custom/Custom.yaml
  schema/custom-codec-schema.json
  schema/protocol-schema.json
Labels: 2.x, Type: Cleanup

#295 member version from int to byte
  protocol-definitions/custom/Custom.yaml
Labels: 2.x

#301 change the name of the uuid and wrong stated doc
  protocol-definitions/Client.yaml
Labels: 2.x
