Repository hazelcast/hazelcast-client-protocol, pull requests merged in 2020-10, with the labels that each got.

#347 Add List with Nullable items support to client protocol
  binary/util.py
  java/__init__.py
  schema/custom-codec-schema.json
  schema/protocol-schema.json
  util.py
Labels: 2.x

#348 Enable CP codecs for C++ client
  cpp/__init__.py
  cpp/header_includes.txt
Labels: Type: Enhancement

#341 add python client codec templates
  binary/__init__.py
  generator.py
  py/__init__.py
  py/codec-template.py.j2
  py/custom-codec-template.py.j2
  util.py
Labels: 2.x, Type: Enhancement

#350 Fix misaligned Javadocs and removed unused field definition for single request parameters
  java/codec-template.java.j2
Labels: 2.x, Type: Cleanup

#353 Improve ignorelist functionality
  cpp/__init__.py
  cs/__init__.py
  py/__init__.py
  ts/__init__.py
  util.py
Labels: 2.x
