Repository hazelcast/hazelcast-client-protocol, pull requests merged in 2021-01, with the labels that each got.

#364 Disable unused methods of the services for C++ codecs generation, remove the `using namespace` statements
  cpp/__init__.py
  cpp/codec-template.cpp.j2
  cpp/header_includes.txt
  cpp/source_header.txt
Labels: Type: Enhancement

#365 Ignore unused codecs for Python client
  py/__init__.py
Labels: 2.x, Type: Cleanup

#367 Update copyright year for Node.js client
  ts/codec-template.ts.j2
  ts/custom-codec-template.ts.j2
Labels: Type: Cleanup

#368 Improve description for client statistics
  protocol-definitions/Client.yaml
Labels: Type: Cleanup

#299 added documentation template
  README.md
  binary/util.py
  binary_generator.py
  cs/__init__.py
  generator.py
  md/__init__.py
  md/documentation-template.j2
  util.py
Labels: 2.x
