Repository hazelcast/hazelcast-client-protocol, pull requests merged in 2023-12, with the labels that each got.

#487 Add declarative Jet Pipeline definition message [API-2167]
  protocol-definitions/Experimental.yaml
Labels: Type: Enhancement

#490 Adapt Hazelcast protocol for Namespaces introduction
  binary/__init__.py
  binary/util.py
  cs/__init__.py
  java/__init__.py
  protocol-definitions/DynamicConfig.yaml
  protocol-definitions/custom/Custom.yaml
  schema/protocol-schema.json
  ts/__init__.py
Labels: Type: Enhancement, 2.x

#493 Change int field for `ExperimentalPipelineSubmitCodec.resourceBundleChecksum` as not nullable
  protocol-definitions/Experimental.yaml
Labels: Type: Defect

#495 Rename `namespace` to `userCodeNamespace` in various places
  protocol-definitions/DynamicConfig.yaml
  protocol-definitions/custom/Custom.yaml
Labels: Type: Enhancement
