Repository hazelcast/hazelcast-client-protocol, pull requests merged in 2024-01, with the labels that each got.

#499 Make non-Java clients copyright year dynamic
  cpp/custom-codec-template.cpp.j2
  cpp/footer.j2
  cpp/header_includes.j2
  cpp/source_header.j2
  md/documentation-template.j2
  ts/custom-codec-template.ts.j2
  util.py
Labels: Type: Cleanup

#500 Make Java clients copyright year dynamic
  java/binary/client-binary-compatibility-template.j2
  java/binary/member-binary-compatibility-template.j2
  java/codec-template.java.j2
  java/custom-codec-template.java.j2
Labels: Type: Cleanup

#502 Remove `removeUserCodeNamespaceConfig` task [HZ-4176]
  protocol-definitions/DynamicConfig.yaml
Labels: Type: Enhancement, Type: Cleanup

#489 Add ReplicatedMapEntryView custom type & ReplicatedMap.putAllWithMetadata [HZ-3934]
  binary/__init__.py
  binary/util.py
  cpp/__init__.py
  cs/__init__.py
  java/__init__.py
  protocol-definitions/ReplicatedMap.yaml
  protocol-definitions/custom/Custom.yaml
  schema/protocol-schema.json
  ts/__init__.py
Labels: Type: Enhancement

#492 ReplicatedMap fetchEntryViews API [HZ-3932]
  protocol-definitions/ReplicatedMap.yaml
Labels: Type: Enhancement
